### PR TITLE
added the readme file

### PR DESCRIPTION
**Pull request by nasben64**

### CODE REVIEW

**Review by HannahBurks — COMMENTED** [review]
Hey Nasser. Great start! You may also need to have another look at where users is on the component tree, as the users page/component will also need access to the reviews according to your plan. Along with this, we would also like to see where about in the component tree those states will be stored. Please make these tweaks and then send over another pull request :D

**Comment by nasben64** [comment]
The reviews can be displayed by users and by categories so I am not sure how to structure this relation any hints please

**Review by emilyb93 — COMMENTED** [review]
Hi Nasser, i like your wireframe, but when it comes to your component tree, think less about what components LINKS to each other, and more about which component is going to be rendered inside another component. 

For instance; will the users page, actively render the list of reviews, or is this going to be on a different page that you link to? It makes sense for comments to be rendered by a reviews page, but is a single review page going to be rendered by the categories/review list page, or again are they going to just link to another page?

Consider something like this 
image

**Review by hevdevs — APPROVED** [review]
Looks brill Nasser! Good to start coding

**Pull request merged**
